[features]
seeds = false
skip-lint = false
[programs.localnet]
surf = "FjWGJ4ecVHR9R39kaGZJcRs4rcBcjDzckvjA7WSBmLsE"
pyth = "DAnkD4WXvcKUULtiakqAxAFwzbpootovrm8rVmZETJu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

validator = "chmod +x ./scripts/solana-test-validator.sh && ./scripts/solana-test-validator.sh"
build-watch = "chmod +x ./scripts/anchor-build.sh && find programs | entr -c ./scripts/anchor-build.sh"
test-new = "anchor deploy && npm run test"

[[test.genesis]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"
program = "./cpi-programs/drift.so"

[[test.genesis]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "./cpi-programs/whirlpool.so"
