[features]
seeds = false
skip-lint = false
[programs.localnet]
surf = "4wVrbfSHxmhevzPzNfdpmVkJ2jqNRy6RYt4TxcHsnfSo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[[test.genesis]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"
program = "./cpi-programs/drift.so"

[[test.genesis]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "./cpi-programs/whirlpool.so"

[[test.genesis]]
address = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"
program = "./cpi-programs/pyth.so"
